<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!-- Infrastructure nhận contract từ Application để cung cấp implementation đúng interface repository/service/realtime. -->
    <ProjectReference Include="..\ChatApp.Application\ChatApp.Application.csproj" />
    <!-- Infrastructure dùng entity/domain rule từ Domain để lưu trữ và thao tác dữ liệu đúng mô hình nghiệp vụ. -->
    <ProjectReference Include="..\ChatApp.Domain\ChatApp.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- FrameworkReference này cho phép project Infrastructure dùng DI/config/logging abstraction khi đăng ký service kỹ thuật. -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
